name: Mideau
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74325
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#21242b'
    - '#2d4d80'
    - '#4c7ca0'
    - '#9eb8c5'
    - '#876e7c'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: 6fcc01d0-8107-4d52-806d-f81005ebd382
    url: null
