name: Mideau
favicon: null
layout_spectrum: 0.62703
typography_spectrum: 0.74325
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#21242b'
    - '#2d4d80'
    - '#4c7ca0'
    - '#9eb8c5'
    - '#876e7c'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: efb7a54e-c0c2-4b10-a7bf-2509550fad0d
    url: null
