name: Mideau
favicon: null
layout_spectrum: 0.62703
typography_spectrum: 0.74325
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8c8fa'
    - '#1d91e8'
    - '#126edb'
    - '#e8b1ce'
    - '#da9182'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: efb7a54e-c0c2-4b10-a7bf-2509550fad0d
    url: null
