name: null
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#434343'
    - '#97ced5'
    - '#606060'
    - '#fafafa'
    - '#919191'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: efb7a54e-c0c2-4b10-a7bf-2509550fad0d
    url: null
